### ISSUE TITLE
Composer not recognized

### ISSUE THREAD

**Issue by JoniAllaert1703** [matthiasnoback/building-autonomous-services-workshop#23]
Dear Matthias,

Apologies for the late notice.
I'm having trouble getting the project to work. I am using Windows and have already encountered some hick ups, but I don't seem to find any information to fix the latetst one I ran into:
C:\Users\jonia\building-autonomous-services-workshop>make up
process_begin: CreateProcess(NULL, uname -s, ...) failed.
process_begin: CreateProcess(NULL, id -u, ...) failed.
process_begin: CreateProcess(NULL, id -g, ...) failed.
(grep "127.0.0.1 dashboard.localhost sales.localhost purchase.localhost catalog.localhost stock.localhost" /etc/hosts) || echo '127.0.0.1 dashboard.localhost sales.localhost purchase.localhost catalog.localhost stock.localhost' | sudo tee -a /etc/hosts
127.0.0.1 dashboard.localhost sales.localhost purchase.localhost catalog.localhost stock.localhost
mkdir -p ~/.composer
The syntax of the command is incorrect.
make: *** [~/.composer] Fout 1

I have Docker desktop for windows and this contains the docker compose as instructed on the docker website. Do you have any tip how to solve this?

Thank you in advance.

Kind regards

Joni

**Comment by matthiasnoback** [comment]
Hi Joni, no problem. I find that on Windows it works best if you use Git Bash (which comes with Git for Windows). That shell behaves more like the one on Linux and Mac. Could you try that first?

**Comment by JoniAllaert1703** [comment]
Hi Matthias,

I'm now using GIT Bash and run into the following problem with the composer:

$ make up
makefile:27: You have to manually add 127.0.0.1 dashboard.localhost sales.localhost purchase.localhost catalog.localhost stock.localhost to your hosts file
mkdir -p ~/.composer
docker run --rm --interactive --tty --volume `pwd`:/app:cached --volume ~/.composer:/tmp:cached --user 197609:197609 composer:latest install
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Mount denied:
The source path "C:/Users/jonia/.composer;C"
doesn't exist and is not known to Docker.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
make: *** [vendor] Fout 125

I looked it up and they propose to add two slashes before the directory but that doesn't seem to work since it does not recognize the path this way. Any idea, what can resolve this? 

I will keep looking and will update if I find something myself

**Comment by matthiasnoback** [comment]
Okay, in that case you could remove the part where it says:

-v ~/.composer:/tmp:cached

It's not strictly needed to mount your Composer home dir into the container.

**Comment by JoniAllaert1703** [comment]
Thank you,

i just found 
$ export MSYS_NO_PATHCONV=1

$ ("docker-compose.exe" "$@")

This worked to get by the composer error. I will leave it as for now, but I will remember your tip.
I'm trying to solve a firewall issue for the sharing: Drive sharing seems blocked by a firewall. This is due to the Norton antivirus from what I read.

**Comment by matthiasnoback** [comment]
That's a problem I've seen before but don't know the solution for. It's
likely googleable though. Good luck!

**Comment by JoniAllaert1703** [comment]
It works thank you very much for the assistance.

**Comment by matthiasnoback** [comment]
Nice! You're welcome.

**Comment by matthiasnoback** [comment]
Closing this, since the modified setup doesn't try to mount the home directory anymore.
