### ISSUE TITLE
Suggestion: Using also localhost:8080

### ISSUE THREAD

**Issue by dereuromark** [matthiasnoback/building-autonomous-services-workshop#45]
> Docker says: "Bind for 0.0.0.0:80 failed: port is already allocated

I also ran into that one, and it is not always trivial to find/close the service in question

I was wondering if we could just use the more simple installation steps as per https://github.com/matthiasnoback/layers-ports-and-adapters-workshop/#option-1-docker

`Open http://localhost:8080` always works super esily and without conflicts of port 80.

**Comment by matthiasnoback** [comment]
See #47. It's certainly an option, but I wouldn't like to change the whole setup at this moment. But, if it gets people into trouble once more, I'll change it.
