### ISSUE TITLE
[Docs] Missing hosts binding step

### ISSUE THREAD

**Issue by gund** [matthiasnoback/building-autonomous-services-workshop#47]
After the install and start of the app - the links will not work as they are custom domains that require to set them in hosts of the OS.

So there should be a step that lists domains which should be added to the local OS hosts file:

```
127.0.0.1 dashboard.localtest.me
127.0.0.1 catalog.localtest.me
127.0.0.1 stock.localtest.me
127.0.0.1 sales.localtest.me
127.0.0.1 purchase.localtest.me
```

Also another suggestion would be to get rid of the domain names and instead expose the ports from docker containers to host OS to be able to use URLs like `localhost:9001`, `localhost:9002`, etc.

**Comment by matthiasnoback** [comment]
Added this to the readme, thanks for reporting. For now I'll stick to subdomains, if it doesn't work well the next time, I promise to migrate to the ports-based mechanism :)
