### ISSUE TITLE
ERROR: Service '...' needs to be built, but --no-build was passed.

### ISSUE THREAD

**Issue by SiebelsTim** [matthiasnoback/building-autonomous-services-workshop#54]
After running `bin/start`, I get the following error:

```
Creating network "building-autonomous-services-workshop_default" with the default driver
Creating network "building-autonomous-services-workshop_traefik" with the default driver
ERROR: Service 'catalog_php' needs to be built, but --no-build was passed.
```

When rerunning the command, it cycles through different services that need to be built.

Removing the `--no-build` flag, or separately building the containers, resolves the issue. 

I don't know why you pass the `--no-build` flag. I assume this is for good reason. Therefore, I think the problem could be fixed in the documentation.

**Comment by matthiasnoback** [comment]
Did you run `docker-compose pull`? Because you shouldn't have to build your own images locally.

**Comment by SiebelsTim** [comment]
I did not. I followed the 4 steps in the README. 
Should this be fixed in the documentation then?

**Comment by matthiasnoback** [comment]
I can't explain this. `docker-compose pull` is part of `bin/install`, did you run that as well?

**Comment by SiebelsTim** [comment]
```
$ ./bin/install                                                                                              
Pulling Docker images
Installing Composer dependencies
docker.io/library/composer:latest
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 95 installs, 0 updates, 0 removals
  - Downloading behat/gherkin (v4.8.0)
[...]
Generating autoload files
59 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
$ ./bin/start                                                                                        
Creating network "building-autonomous-services-workshop_default" with the default driver
Creating network "building-autonomous-services-workshop_traefik" with the default driver
ERROR: Service 'process_manager' needs to be built, but --no-build was passed.
```

Apparently, its only pulling ingress:

```
$ docker-compose -f docker-compose.web.yml -f docker-compose.consumers.yml pull                             
Pulling ingress ... done

**Comment by matthiasnoback** [comment]
Thanks for looking into it. It's really weird... I guess the solution would be to pull the separate images.

**Comment by SiebelsTim** [comment]
It appears to be the fault of the `build` declaration. If I remove `build: docker/php-fpm` from the docker-compose files, it pulls all of them.

Can we remove them, as the workshop attendees aren't supposed to build them?

**Comment by matthiasnoback** [comment]
I've switch to separate `docker pull` calls just to be sure. I can't imagine why `docker/php-fpm` would be an issue, apart from maybe the `-` (actually, that might be a Yaml problem?). Anyway, it's fixed now I'd say.

**Comment by SiebelsTim** [comment]
I don't think it's about docker/php-fpm, but rather that they have a `build:` instruction.

Nevertheless, I can confirm that it's fixed :)

**Comment by matthiasnoback** [comment]
Ah, I see what you mean! They probably need to be separated then. Thanks again!
