### ISSUE TITLE
bin/stop default argument does not find service

### ISSUE THREAD

**Issue by SiebelsTim** [matthiasnoback/building-autonomous-services-workshop#55]
```
$ ./bin/stop                         
ERROR: No such service: 
```

`bin/stop` tries to offer a default value to stop all services. However, as the argument is enclosed in quotes, the shell will pass the empty string as an argument, as opposed to omitting the argument.

Omitting the quotes in combination with using `$@` might be a solution to allow passing multiple service names.

**Comment by matthiasnoback** [comment]
Ah but it's supposed to be stopping only one service at a time (for demonstration purposes basically). If you want to stop them all, there's `bin/down`.

**Comment by SiebelsTim** [comment]
Okay. Why does it offer a default value for `$1` then? Shouldn't it rather display a help text?

**Comment by matthiasnoback** [comment]
Ah I see now what the issue is, sorry. Just fixed it.
