### ISSUE TITLE
Explain how to run docker without sudo

### ISSUE THREAD

**Issue by SiebelsTim** [matthiasnoback/building-autonomous-services-workshop#56]
A colleague of mine ran into the problem, that he couldn't run docker without `sudo`. 

On linux, to run docker without super user privileges, the desired user needs to be a member of the docker group.
(Tutorial: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user)

I don't know if it is worth it to mention it in the README.

As there are already notes for windows users, there might be a place for linux users as well.

That being said, I'm happy if you want to close this without changes, as this is more of a "how to install docker" kind of thing.

**Comment by matthiasnoback** [comment]
Nice addition, thanks!
